name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download and install MS-MPI for windows
      - name: Install MS-MPI for Windows
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o msmpisetup.exe https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe
          .\msmpisetup.exe -s

      # Install OpenMPI and MPICH for Ubuntu
      - name: Install OpenMPI for Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y openmpi-bin libopenmpi-dev

      # Install OpenMPI and MPICH for macOS
      - name: Install OpenMPI for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install open-mpi

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

      - name: Install package and run tests
        run: |
          python -m pip install -e .
          pytest