name: Build and Deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build Test Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-latest, windows-latest, ubuntu-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download and install MS-MPI for windows
      - name: Install MS-MPI
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o msmpisetup.exe https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe
          .\msmpisetup.exe -s

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt

      - name: Install package and run tests
        run: |
          python -m pip install -e .
          pytest 

      - name: Deploy to PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m twine upload --repository pypi dist/*

